/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesGraficas;

import baseDeDatos.EditarBaseDatos;
import baseDeDatos.EliminarBaseDatos;
import baseDeDatos.GuardarBaseDatos;
import baseDeDatos.MostrarBaseDatos;
import baseDeDatos.MostrarBaseDatosCursos;
import clases.DescuentoRendimientoAcademico;
import clases.DescuentoSituacionEconomica;
import clases.EstrategiaDescuento;
import clases.Estudiante;
import clases.asignatura;
import clases.cursos;
import clases.matricula;
import clases.pensumAcademico;
import clases.programaAcademico;
import clases.semestreAcademico;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.Random;

/**
 *
 * @author edgar
 */
public class EstudianteMatriculaScreen extends javax.swing.JFrame {

    private Estudiante estudiante;
    private programaAcademico ProgramaAcademico;
    
    
    public EstudianteMatriculaScreen(Estudiante estudiante) {
        this.estudiante = estudiante;
        initComponents();
        this.setLocationRelativeTo(null);
        String idEstudiante = estudiante.getNombre();
        //lblNombre.setText(estudiante.getNombre());
        cargarDatosMatricula();
        this.setLocationRelativeTo(null);
        guardarBaseDatos.llenarComboBox(comboBoxPrograma, "programaacademico", "idProgramaAcademico");

    }

    GuardarBaseDatos guardarBaseDatos = new GuardarBaseDatos();
    EliminarBaseDatos eliminarBaseDatos = new EliminarBaseDatos();

    private EstudianteMatriculaScreen() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void cargarDatosMatricula() {
        GuardarBaseDatos dbHandler = new GuardarBaseDatos();
        matricula matricula = dbHandler.obtenerMatriculaEstudiante(estudiante.getNombre());

        // Verificar si matricula es null
        if (matricula == null) {
            JOptionPane.showMessageDialog(rootPane, "No se encontró la matrícula para el estudiante: " + estudiante.getNombre());
            return;
        }

        // Convertir los datos de la matrícula a Vector<Vector<String>>
        Vector<Vector<String>> tableData = new Vector<>();
        Vector<String> row = new Vector<>();
        row.add(matricula.programaAcademico.nombrePrograma);
        if (matricula.estrategiaDescuento != null) {
            if (matricula.estrategiaDescuento instanceof DescuentoRendimientoAcademico) {
                row.add("Descuento rendimiento");
            } else if (matricula.estrategiaDescuento instanceof DescuentoSituacionEconomica) {
                row.add("Descuento situacion economica");
            }
        } else {
            row.add("No hay descuento");
        }
        row.add(Float.toString(matricula.getCostoMatricula()));
        row.add(matricula.getEstadoMatricula());
        tableData.add(row);

        // Crear un Vector<String> para las columnas
        Vector<String> columnNames = new Vector<>();
        columnNames.add("Programa Académico");
        columnNames.add("Tipo de Descuento");
        columnNames.add("Costo de Matrícula");
        columnNames.add("Estado de Matrícula");

        DefaultTableModel dtm = new DefaultTableModel(tableData, columnNames);
        tableMatricula.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPagarMatricula = new javax.swing.JButton();
        btnCrearMatricula = new javax.swing.JButton();
        txtCostoMatricula = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMatricula = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        comboBoxPrograma = new javax.swing.JComboBox<>();
        comboBoxDescuento = new javax.swing.JComboBox<>();
        txtPrueba = new javax.swing.JLabel();
        txtPrecioNormal = new javax.swing.JTextField();

        jLabel6.setText("Nivel Academico:");

        jButton4.setText("Buscar");

        jLabel8.setText("Programa Academico:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        btnPagarMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pagar.png"))); // NOI18N
        btnPagarMatricula.setText("Pagar");
        btnPagarMatricula.setBorder(null);
        btnPagarMatricula.setBorderPainted(false);
        btnPagarMatricula.setContentAreaFilled(false);
        btnPagarMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPagarMatricula.setEnabled(false);
        btnPagarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarMatriculaActionPerformed(evt);
            }
        });

        btnCrearMatricula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crearObjeto.png"))); // NOI18N
        btnCrearMatricula.setText("Crear");
        btnCrearMatricula.setBorder(null);
        btnCrearMatricula.setBorderPainted(false);
        btnCrearMatricula.setContentAreaFilled(false);
        btnCrearMatricula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearMatriculaActionPerformed(evt);
            }
        });

        txtCostoMatricula.setBackground(new java.awt.Color(0, 153, 255));
        txtCostoMatricula.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio con descuento"));

        jScrollPane2.setViewportView(tableMatricula);

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seccion Matricula");

        btnRegresar.setBackground(new java.awt.Color(0, 153, 204));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 477, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar)
                    .addComponent(jLabel1))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        comboBoxPrograma.setBackground(new java.awt.Color(0, 153, 255));
        comboBoxPrograma.setBorder(javax.swing.BorderFactory.createTitledBorder("Id Programa"));

        comboBoxDescuento.setBackground(new java.awt.Color(0, 153, 255));
        comboBoxDescuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Descuento rendimiento", "Descuento situacion economica" }));
        comboBoxDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDescuentoActionPerformed(evt);
            }
        });

        txtPrueba.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero de transaccion"));

        txtPrecioNormal.setBackground(new java.awt.Color(0, 153, 255));
        txtPrecioNormal.setBorder(javax.swing.BorderFactory.createTitledBorder("Precio Normal"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnCrearMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnPagarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxDescuento, 0, 0, Short.MAX_VALUE)
                    .addComponent(comboBoxPrograma, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPrecioNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(txtCostoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCostoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(comboBoxPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(comboBoxDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearMatricula)
                    .addComponent(btnPagarMatricula))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private HashSet<Integer> numerosGenerados = new HashSet<>();

    private void btnCrearMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearMatriculaActionPerformed
        // TODO add your handling code here:

        // Obtener el programa académico seleccionado de la base de datos
        String idProgramaSeleccionado = (String) comboBoxPrograma.getSelectedItem();
        programaAcademico programaAcademico = guardarBaseDatos.obtenerProgramaAcademicoDeLaBaseDeDatos(idProgramaSeleccionado);

        // Verificar si el estudiante está en el programa
        if (!guardarBaseDatos.esEstudianteEnPrograma(estudiante.getNombre(), idProgramaSeleccionado)) {
            JOptionPane.showMessageDialog(rootPane, "No puedes matricularte en un programa al que tu curso no pertenece.");
            return;
        }
        // Obtener el descuento seleccionado
        String descuentoSeleccionado = (String) comboBoxDescuento.getSelectedItem();
        EstrategiaDescuento estrategiaDescuento = null;
        if (descuentoSeleccionado != null) {
            if (descuentoSeleccionado.equals("Descuento rendimiento")) {
                estrategiaDescuento = new DescuentoRendimientoAcademico();
            } else if (descuentoSeleccionado.equals("Descuento situacion economica")) {
                estrategiaDescuento = new DescuentoSituacionEconomica();
            }
        }

        // Si estrategiaDescuento es null, mostrar un mensaje de error y retornar
        if (estrategiaDescuento == null) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, selecciona un descuento.");
            return;
        }

        // Crear una matrícula y calcular el costo
        matricula matricula = new matricula(programaAcademico, estrategiaDescuento);
        matricula.calcularMatricula();

        // Establecer el estado de la matrícula a "PENDIENTE"
        matricula.setEstadoMatricula("PENDIENTE");

        // Guardar la matrícula usando el nombre del estudiante
        guardarBaseDatos.guardarMatriculaPorNombre(matricula, estudiante.getNombre());

        // Generar un número aleatorio único de más de 6 dígitos
        Random rand = new Random();
        int numeroAleatorio;
        do {
            numeroAleatorio = 1000000 + rand.nextInt(9000000);  // Genera un número aleatorio entre 1000000 y 9999999
        } while (numerosGenerados.contains(numeroAleatorio));
        numerosGenerados.add(numeroAleatorio);

        // Mostrar el número aleatorio en el JTextField txtPrueba
        txtPrueba.setText(Integer.toString(numeroAleatorio));
        
        txtPrecioNormal.setText(Float.toString(programaAcademico.getTarifaBase()));
        // Mostrar el costo en el JTextField
        txtCostoMatricula.setText(Float.toString(matricula.getCostoMatricula()));

        btnPagarMatricula.setEnabled(true);

        JOptionPane.showMessageDialog(rootPane, "Tu matricula esta " + matricula.getEstadoMatricula() + " por aprobacion, por favor realiza "
                + "el pago de la misma para poder continuar de todos los procesos academicos");
        cargarDatosMatricula();


    }//GEN-LAST:event_btnCrearMatriculaActionPerformed

    private void btnPagarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarMatriculaActionPerformed
        // TODO add your handling code here:
        EstudianteMatriculaPago emp = new EstudianteMatriculaPago(this.estudiante);

        emp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPagarMatriculaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        MainEstudianteScreen adm = new MainEstudianteScreen(this.estudiante);
        adm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void comboBoxDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDescuentoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_comboBoxDescuentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudianteMatriculaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudianteMatriculaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudianteMatriculaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudianteMatriculaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudianteMatriculaScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearMatricula;
    private javax.swing.JButton btnPagarMatricula;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> comboBoxDescuento;
    private javax.swing.JComboBox<String> comboBoxPrograma;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableMatricula;
    private javax.swing.JTextField txtCostoMatricula;
    private javax.swing.JTextField txtPrecioNormal;
    private javax.swing.JLabel txtPrueba;
    // End of variables declaration//GEN-END:variables
}
