/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfacesGraficas;

import baseDeDatos.MostrarBaseDatos;
import clases.Estudiante;
import clases.asignatura;
import clases.programaAcademico;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.HashSet;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author edgar
 */
public class EstudianteAsignaturaScreen extends javax.swing.JFrame {

    private Estudiante estudiante;
    private programaAcademico ProgramaAcademico;
    private DefaultListModel<String> listModel;

    public EstudianteAsignaturaScreen(Estudiante estudiante) {
        this.estudiante = estudiante;
        initComponents();
        this.setLocationRelativeTo(null);
        String idEstudiante = estudiante.getNombre();
        this.setLocationRelativeTo(null);

        // Crear el modelo de la lista y asignarlo a listAsignaturas
        listModel = new DefaultListModel<>();
        listAsignaturas.setModel(listModel);

        // Obtener las asignaturas del estudiante y añadirlas a la lista
        List<String> asignaturas = mostrarBaseDatos.obtenerAsignaturasEstudiante(idEstudiante);
        for (String asignatura : asignaturas) {
            listModel.addElement(asignatura);
        }

        // Crear un nuevo modelo de tabla
        DefaultTableModel model = new DefaultTableModel();

        // Añadir las columnas al modelo
        model.addColumn("Nombre de la Asignatura");
        model.addColumn("Día");
        model.addColumn("Hora de Inicio");
        model.addColumn("Hora de Fin");

        // Asignar el modelo a la tabla
        tableAsignaturasEstudiantes.setModel(model);

        nombreEstudiante.setText("Bienvenido: " + estudiante.getNombre() + " " + estudiante.getApellido() + " a continuacion selecciona"
                + " las asignaturas que vas a ver este semestre");

    }

    private void listAsignaturasValueChanged(javax.swing.event.ListSelectionEvent evt) {
        String nombreAsignatura = listAsignaturas.getSelectedValue();
        asignatura asignatura = mostrarBaseDatos.obtenerAsignatura(nombreAsignatura);

        for (int i = 0; i < tableAsignaturasEstudiantes.getRowCount(); i++) {
            if (tableAsignaturasEstudiantes.getValueAt(i, 1).equals(asignatura.getDia())
                    && tableAsignaturasEstudiantes.getValueAt(i, 2).equals(asignatura.getHoraInicio())
                    && tableAsignaturasEstudiantes.getValueAt(i, 3).equals(asignatura.getHoraFin())) {
                JOptionPane.showMessageDialog(this, "No se pueden matricular: " + nombreAsignatura + " por motivo de cruce de horario", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        DefaultTableModel model = (DefaultTableModel) tableAsignaturasEstudiantes.getModel();
        model.addRow(new Object[]{asignatura.getNombreAsignatura(), asignatura.getDia(), asignatura.getHoraInicio(), asignatura.getHoraFin()});
    }

    MostrarBaseDatos mostrarBaseDatos = new MostrarBaseDatos();

    private EstudianteAsignaturaScreen() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnConfirmarAsignaturas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAsignaturas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableAsignaturasEstudiantes = new javax.swing.JTable();
        nombreEstudiante = new javax.swing.JLabel();

        jLabel6.setText("Nivel Academico:");

        jButton4.setText("Buscar");

        jLabel8.setText("Programa Academico:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        btnConfirmarAsignaturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/crearObjeto.png"))); // NOI18N
        btnConfirmarAsignaturas.setText("Crear");
        btnConfirmarAsignaturas.setBorder(null);
        btnConfirmarAsignaturas.setBorderPainted(false);
        btnConfirmarAsignaturas.setContentAreaFilled(false);
        btnConfirmarAsignaturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConfirmarAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarAsignaturasActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seccion Asignaturas");

        btnRegresar.setBackground(new java.awt.Color(0, 153, 204));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 477, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar)
                    .addComponent(jLabel1))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        listAsignaturas.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione las materias"));
        jScrollPane1.setViewportView(listAsignaturas);

        jScrollPane2.setViewportView(tableAsignaturasEstudiantes);

        nombreEstudiante.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnConfirmarAsignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(nombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(nombreEstudiante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnConfirmarAsignaturas)
                        .addGap(103, 103, 103))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private HashSet<Integer> numerosGenerados = new HashSet<>();


    private void btnConfirmarAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarAsignaturasActionPerformed
        // TODO add your handling code here:
        if (tableAsignaturasEstudiantes.getColumnCount() >= 4) {
            List<String> nombresAsignaturas = listAsignaturas.getSelectedValuesList();
            for (String nombreAsignatura : nombresAsignaturas) {
                asignatura asignatura = mostrarBaseDatos.obtenerAsignatura(nombreAsignatura);

                for (int i = 0; i < tableAsignaturasEstudiantes.getRowCount(); i++) {
                    if (tableAsignaturasEstudiantes.getValueAt(i, 1).equals(asignatura.getDia())
                            && tableAsignaturasEstudiantes.getValueAt(i, 2).equals(asignatura.getHoraInicio())
                            && tableAsignaturasEstudiantes.getValueAt(i, 3).equals(asignatura.getHoraFin())) {
                        JOptionPane.showMessageDialog(this, "No se pueden matricular: " + nombreAsignatura + " por motivo de cruce de horario", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }

                DefaultTableModel model = (DefaultTableModel) tableAsignaturasEstudiantes.getModel();
                model.addRow(new Object[]{asignatura.getNombreAsignatura(), asignatura.getDia(), asignatura.getHoraInicio(), asignatura.getHoraFin()});
            }
        }
    }//GEN-LAST:event_btnConfirmarAsignaturasActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        MainEstudianteScreen adm = new MainEstudianteScreen(this.estudiante);
        adm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudianteAsignaturaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudianteAsignaturaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudianteAsignaturaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudianteAsignaturaScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudianteAsignaturaScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarAsignaturas;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listAsignaturas;
    private javax.swing.JLabel nombreEstudiante;
    private javax.swing.JTable tableAsignaturasEstudiantes;
    // End of variables declaration//GEN-END:variables
}
